using AutoMapper;
using msEmpresaMongoDB.DTO;
using msEmpresaMongoDB.Entity;

namespace msEmpresaMongoDB.Mapper
{
    public class EmpresaProfile : Profile
    {
        // RequestDTO -> Entity
        public EmpresaProfile()
        {
            // RequestDTO -> Entity
            CreateMap<EmpresaRequestDTO, Empresa>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()); // Id will be generated by Mongo

            // Entity -> ResponseDTO
            CreateMap<Empresa, EmpresaResponseDTO>();
        }
    }
}
